name: Duplicate Issue to Dev Dashboard

on:
  push:
    branches:
      - fix-issue

jobs:
  duplicate_issue:
    name: duplicate_issue
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Title and Body
      id: issue-params
      run: |   
        set -o xtrace
        cat > issue.md<<- 'EOM'
        -$(echo Mooo)

        ---

        This issue is related to public issue:
        * https://github.com/chain4travel/camino-public-issues/issues/${{ github.event.issue.number }}
        EOM
        ISSUE_BODY=$(cat issue.md)
        cat > title.md<<- 'EOM'
        title-mo
        EOM
        export TITLE=$(cat title.md)
        export BODY=${ISSUE_BODY//['"']/'\"'}

        echo "preoutput"
        
        echo "issue_title<<'EOM'" >> $GITHUB_OUTPUT
        echo "$TITLE" >> $GITHUB_OUTPUT
        echo "EOM" >> $GITHUB_OUTPUT
        
        echo "issue_body<<'EOF'" >> $GITHUB_OUTPUT        
        echo "$BODY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "DonnnnEEE"

        echo "$BODY"
        echo "$TITLE"
        cat $GITHUB_OUTPUT
        

    - name: Create Private Issue
      run: |        
        echo "${{ steps.issue-params.outputs.issue_title }}"
        echo "${{ steps.issue-params.outputs.issue_body }}"

